### ISSUE TITLE
Relating to #1, Create a component that accepts 2 dates and formats it as a range

### ISSUE THREAD

**Issue by jonathan-irvin** [denmanma/react-resume#3]
# DateRange Component

`<DateRange start={any moment of time} start={any moment of time} />`

# Output Example:

OCT 2005 - FEB 2012

**Comment by denmanma** [comment]
Note: If the end date is missing, then output "Present" ~Jonathan

**Comment by denmanma** [comment]
https://momentjs.com/ Library for date formatting
