### ISSUE TITLE
Create a Bullets Component that accepts an array and outputs an unordered list

### ISSUE THREAD

**Issue by jonathan-irvin** [denmanma/react-resume#4]
**Expectation:**
<Bullets points={array of strings}/>

**Output:**
<ul>
    <li>Bullet 1</li>
    <li>Bullet 2</li>
    ....
</ul>

**Reference**: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

Look at .map() and .forEach()
**hint** map is faster ;)

**Comment by denmanma** [comment]
fixed by commit 3cb6be40d384be62ddf45aff5a850f55b06ee187
